### ISSUE TITLE
Authentication errors

### ISSUE THREAD

**Issue by andreewa** [takeyamajp/docker-postfix#2]
I install everything according to the instructions, but then I write that the login and password are not correct when connecting to the smtp. tried user=test@mydomain.ru user = test

**Comment by takeyamajp** [comment]
Did you check error information in 'docker logs'?
We may be able to give you some advice if we can know what kind of errors are output.
You had better check your network environments, if those have been not output.

**Comment by ghost** [comment]
@takeyamajp I am reproduced the issue today. i found the image without any tag is broken. but if we change using rocky8, it lookss good.

```
version: '3.9'  
services:  
  postfix:  
    image: "takeyamajp/postfix:rocky8"
    container_name: postfix
    restart: always
    ports:  
   #- "8587:587"  
      - "127.0.0.1:8465:465"  
    volumes:  
      - ./certs:/ssl_certs  
      - ./keys:/dkim_keys  
    environment:  
      TIMEZONE: "Asia/Hongkong"  
      HOSTNAME: "smtpdot.domain.com"  
      DOMAIN_NAME: "domain.com"  
      MESSAGE_SIZE_LIMIT: "10240000"  
      AUTH_USER: "name"  
      AUTH_PASSWORD: "password"  
      #    DISABLE_SMTP_AUTH_ON_PORT_25: "true"  
      ENABLE_DKIM: "true"  
      DKIM_KEY_LENGTH: "1024"  
      DKIM_SELECTOR: "default"
```
